### ISSUE TITLE
Show version in output

### ISSUE THREAD

**Issue by djt** [bananaml/banana-cli#5]
Currently need to look at pip freeze to identify the current running version.  Would be great if all commands indicated current version.

Other alternative is to have banana version or banana -v.

**Comment by erik-dunteman** [comment]
will do, thanks

**Comment by johntharian** [comment]
Hey, I tried solving this, I have added a pr as well https://github.com/bananaml/banana-cli/pull/22

**Comment by nik-418** [comment]
This has been implemented as a `--version` flag in a recent update using the native click package decorator. 👍
